services:
  postgres:
    image: postgres:latest
    container_name: postgres_integracion
    environment:
      POSTGRES_DB: integracion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    image: integracion:latest
    container_name: integracion_spring_boot
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: