spring:
  profiles:
    active: dev
  application:
    name: vientos-del-sur
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: never
      continue-on-error: false
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:sql/data.sql
  keys:
    jwt-secret-key: ${JWT_SECRET_KEY}
    open-weather-api-key: ${OPEN_WEATHER_API_KEY}