package com.f776.vientosdelsur.api.user;

public enum Role {
    ROLE_VENTAS_ADMIN,
    ROLE_VENTAS_USER,
    ROLE_PROVEEDOR_ADMIN,
    ROLE_PROVEEDOR_ADQUISICION,
    ROLE_PROVEEDOR_USER,
    ROLE_POST_VENTA_USER,
    ROLE_POST_VENTA_ADMIN,
    ROLE_CONTABILIDAD_ADMIN,
    ROLE_CONTABILIDAD_USER,
    ROLE_DESPACHO_ADMIN,
    ROLE_DESPACHO_USER,
    ROLE_ADQUISICION_ADMIN,
    ROLE_ADQUISICION_USER,
    ROLE_STOCK_ADMIN,
    ROLE_STOCK_USER,
    ROLE_REPORTERIA_ADMIN,
    ROLE_REPORTERIA_USER
}
